coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - JWTDecodeTests/*
    - JWTDecode.playground/*
  status:
    patch:
      default:
        threshold: 50
        if_no_uploads: error
    changes: true
    project:
      default:
        target: auto
        threshold: 2
        if_no_uploads: error
comment: false
